---
title: "STT 3530 (Data Science I) Course Schedule"
author: "Alan T. Arnholt"
date: 'Last compiled: `r format(Sys.time(), "%A, %B %d, %Y - %X.")`'
output: 
  html_document: 
    highlight: textmate
    theme: yeti
    css: "../css/style.css"
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

### General Notes: {-}

```{block, note-text, type='rmdnote'}
1.  Please bring a notebook and pencil to every class.  
2.  You do not need to purchase a text for this course.
3.  Access the [DataCamp](https://datacamp.com) assignments via [AsULearn](https://asulearn.appstate.edu)
```


## Week 1: (Aug 22, Aug 24) {-}


* Sign-up for a free account on [GitHub](https://github.com).

* When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **FirstNameLastName** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinquishing characteristic in your username.   

* _Complete Introduction to R_ [(DataCamp)](https://datacamp.com)

* _Introduction to R_ [slides](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/IntroToR.html)  
 
```{block, week1optional, type='rmdoptional'}
#### Optional {-}
* You may want to install [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), [zotero](https://www.zotero.org), and optionally [$LaTeX$](http://www.ctan.org/starter) on your personal computer. If you do, you will want to follow Jenny Bryan's excellent advice for [installing R and RStudio](http://stat545-ubc.github.io/block000_r-rstudio-install.html) and [installing Git](http://stat545-ubc.github.io/git01_git-install.html).  Jenny's advice is also in chapters 6 and 7 of [Happy Git and GitHub for the useR](http://happygitwithr.com/).  Note: [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), and [$LaTeX$](http://www.ctan.org/starter) are installed on the [Appstate RStudio](https://mathr.math.appstate.edu/) server.

* Watch the following videos as appropriate:

* [Install R on Mac (2 min)](https://www.youtube.com/watch?v=lJxVRgiX-ik)    

* [Install R for Windows (3 min)](https://www.youtube.com/watch?v=LII6of-5Odw)    

* [Install R and RStudio on Windows (5 min)](https://www.youtube.com/watch?v=eD07NznguA4)    

```

## Week 2: (Aug 29, Aug 31) {-}

* Become familiar with the Appstate [RStudio server](https://mathr.math.appstate.edu/). You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.

* Complete _Intermediate R_ [(DataCamp)](https://datacamp.com)


## Week 3 (Sep 5, Sep 7) {-}

* Complete _Reporting with R Markdown_ [(DataCamp)](https://datacamp.com)

* Complete _Working with the Rstudio IDE (Part I)_ [(DataCamp)](https://datacamp.com)

* Test drive RStudio by following the directions from [Jenny Bryan's STAT 545 course](https://stat545-ubc.github.io/git07_git-github-rstudio.html).  Additional material can be found in the detailed `Bookdown` document [Happy Git and GitHub for the useR](http://happygitwithr.com/).  Chapters 8, 10-13 of [Happy Git and GitHub for the useR](http://happygitwithr.com/) will be helpful if you need more directions for test driving RStudio. Note: Git, R, and the RStudio IDE have already been installed for you on the RStudio server.    
* Read the [Git and GitHub](http://r-pkgs.had.co.nz/git.html) chapter from Hadley Wickham's book [R Packages](http://r-pkgs.had.co.nz/)



```{block, week3optional, type='rmdoptional'}
#### Optional {-}
* You may want to install [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), [zotero](https://www.zotero.org), and optionally [$LaTeX$](http://www.ctan.org/starter) on your personal computer. If you do, you will want to follow Jenny Bryan's excellent advice for [installing R and RStudio](http://stat545-ubc.github.io/block000_r-rstudio-install.html) and [installing Git](http://stat545-ubc.github.io/git01_git-install.html).  Jenny's advice is also in chapters 6 and 7 of [Happy Git and GitHub for the useR](http://happygitwithr.com/).  Note: [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), and [$LaTeX$](http://www.ctan.org/starter) are installed on the [Appstate RStudio](https://mathr.math.appstate.edu/) server.
```

```{block, test3, type='rmdexercise'}
Test yourself:

1.
2.
```



## Week 4: (Sep 12, Sep 14) {-}

* Optional _Working with the Rstudio IDE (Part II)_ [(DataCamp)](https://datacamp.com)

* Create a personal web page using [R Markdown](http://rmarkdown.rstudio.com/rmarkdown_websites.html)



## Week 5: (Sep 19, Sep 21) {-}

* Complete _Data Visualization in R_ [(DataCamp)](https://datacamp.com)

## Week 6: (Sep 26, Sep 28) {-}

* Complete _Data Visualization with `ggplot2`_ (Part 1) [(DataCamp)](https://datacamp.com)

## Week 7: (Oct 3, Oct 5) {-}

* Complete _Data Visualization with `ggplot2`_ (Part 2) [(DataCamp)](https://datacamp.com)


## Week 8: (Oct 10; Oct 12 - 13 Fall Break) {-}

* Start Project

```{block, Project, type='rmdnote'}
* Project: [Duplicate Amber Thomas's work on bicycle sharing](https://proquestionasker.github.io/projects/2016/11/10/bicyclesseattle/) - Use your own formatting and publish your analysis on your personal GitHub webpage.
* For additional ideas see: 
  1. Summer Sun's blog [post](http://blog.nycdatascience.com/featured/nyc-citi-bike-migration-visulization/)
  2. Todd Schneider's blog [post](http://toddwschneider.com/posts/taxi-vs-citi-bike-nyc/)
  3. [bikedata](https://ropensci.org/blog/blog/2017/10/17/bikedata) package
  4. [Citibike Business Opportunity: Advertising](https://blog.nycdatascience.com/student-works/citibike-business-opportunity-advertising/)
```

## Week 9: (Oct 17, Oct 19) {-}

* Complete _Data Manipulation in R with `dplyr`_ [(DataCamp)](https://datacamp.com)

## Week 10: (Oct 24, Oct 26) {-}

* Complete _Joining Data in R with `dplyr`_ [(DataCamp)](https://datacamp.com)

## Week 11: (Oct 31,  Nov 2) {-}

* ~~Complete _Importing Data in R (Part 1)_ [(DataCamp)](https://datacamp.com)~~

## Week 12: (Nov 7, Nov 9) {-}

* ~~Complete _Importing Data in R (Part 2)_ [(DataCamp)](https://datacamp.com)~~

* Comment on student's [web pages](http://alanarnholt.github.io/fall17DS1)

## Week 13: (Nov 14, Nov 16) {-}

* ~~Complete _Cleaning Data in R_ [(DataCamp)](https://datacamp.com)~~

* Publish project up to _Trip Routes_

    + Include a link to your GitHub repo on your landing page (possibly using the octocat icon)
    + Use `bookdown::html_document2` for your project
    + Label all Figures and Tables
    + Organize files

## Week 14: (Nov 21; 22-24 Thanksgiving Break) {-}

* ~~Start _Importing & Cleaning Data in R: Case Studies_ [(DataCamp)](https://datacamp.com)~~

* Last day to improve/change grade on DataCamp (Nov 21)

## Week 15: (Nov 28, Nov 30) {-}

* Work on project

* ~~Complete _Importing & Cleaning Data in R: Case Studies_ [(DataCamp)](https://datacamp.com)~~

## Week 16: (Dec 5; Dec 7 is Reading Day) {-}

* Work on project

### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  Follow the TR meeting pattern on the [University Exam Schedule](https://registrar.appstate.edu/sites/registrar.appstate.edu/files/asu_fall_2017_exam_schedule_final_3.pdf) to determine when you will present your Project.
```